# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e84dd163b42fbd0563eef020fbb606d523ae9338045294cfae0c6c776ac3bd17ede96b1d08ed23162c79d2164004ef545c66ad2450a1d10105d359a196c824b3

test:
  secret_key_base: 2255beaad3f2de14c0f9669862f70fdbcedffc75eba75a2278000f5b552c6e557ae4423411765961644f0b6d03aad393abe7cb9282b10639417402305618023b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
